name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Use cached node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run Lint and Tests
        run: yarn lint && yarn test:ci

      - name: Use cached node_modules
        uses: actions/cache@v2
        with:
          path: .next
          key: next-build-${{ github.sha }}
          restore-keys: |
            next-build-

      - name: Build
        run: yarn build
